---
# tasks file for ansible-elixir
- name: install unzip
  package: name=unzip state=present
- name: create elixir {{ elixir_release }} directory
  file:
    path: "{{ base_path }}/elixir-{{ elixir_release }}"
    state: directory
- name: unarchive elixir {{ elixir_release }} binaries
  unarchive:
    src: https://github.com/elixir-lang/elixir/releases/download/v{{ elixir_release }}/Precompiled.zip
    dest: "{{ base_path }}/elixir-{{ elixir_release }}"
    remote_src: 'yes'
    creates: "{{ base_path }}/elixir-{{ elixir_release }}/bin/iex"
- name: set PATH config
  template: src=elixir.sh.j2 dest=/etc/profile.d/elixir.sh
